### ISSUE TITLE
Mauvaise version de node.js

### ISSUE THREAD

**Issue by amoi69** [DavZero/jeedom_plugwise#3]
Bonjour DavZero,

Je n'ai pas vu dans toutes les mises à jour sur mon debian et j'ai laissé passé une mise à jour node.js.
Du coup le plugin Plugwise ne démarre plus car il attend une autre version:

Error: The module '/var/www/html/plugins/plugwise/node/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at bindings (/var/www/html/plugins/plugwise/node/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/var/www/html/plugins/plugwise/node/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)

Comment fairepour solutionner ce problème?

Par avance merci pour ton aide et bonne journée.

**Comment by DavZero** [comment]
Salut,

peux tu forcer la réinstallation des dépendances et m'envoyer le log
complet du démon ainsi que le log d'installation des dépendances.

A+

**Comment by amoi69** [comment]
Bonjour,

J'ai relancé l'installation des dépendances mais cela ne change pas le problème. Je te joins comme demandé les logs.

Je suppose que je dois recompiler quelques choses avec la nouvelle version mais je ne sais pas quoi ni comment faire.

Merci pour ton aide.

A+
[plugwise_dep.txt](https://github.com/DavZero/jeedom_plugwise/files/7155357/plugwise_dep.txt)
[plugwise_deamon.txt](https://github.com/DavZero/jeedom_plugwise/files/7155358/plugwise_deamon.txt)

**Comment by DavZero** [comment]
Ah oui j'avais pas compris, il faut que tu désinstalle nodejs (avec la
commande sudo apt-get purge --auto-remove nodejs) et que tu relance
l'installation du plugin (qui va installer la bonne version de nodejs).

A+

**Comment by amoi69** [comment]
Merci c'était effectivement ce qu'il fallait faire!
J'aurais dû y pensé tout seul...
Très bonne journée et encore merci pour ton aide ;-)
